### ISSUE TITLE
Issues upgrading to Ember 3.24/ember-qunit 5 because of ember-cli-page-object versions

### ISSUE THREAD

**Issue by danwenzel** [Addepar/ember-table#855] opened 2021-01-21 16:06 UTC
In order to upgrade to Ember 3.24 or Qunit 5, an upgrade to ember-cli-page-object v2 is required:

https://github.com/san650/ember-cli-page-object/issues/525
https://github.com/san650/ember-cli-page-object/issues/524

However, `ember-table` has a dependency on `ember-classy-page-object`, which is pinned to an older version of `ember-cli-page-object`.  This causes errors, as these versions are incompatible:

```
Could not find module `ember-test-helpers/wait` imported from `ember-cli-page-object/test-support/-private/execution_context/integration`
```

Would it be possible to remove the hard dependency on `ember-cli-page-object` here, to avoid these issues?

**Comment by mixonic** [comment] 2021-01-21 18:03
@danwenzel thanks for this report.

**Comment by mixonic** [comment] 2021-01-21 20:05
@danwenzel If you do not need support for IE11, please try the 3.0.0-4 beta https://github.com/Addepar/ember-table/releases/tag/v3.0.0-4

Or is this report against the beta? If the bug report is for `master` or 2.x, we will probably close it as a wontfix

**Comment by danwenzel** [comment] 2021-01-21 20:50
@mixonic - I'm afraid the issue does still occur in 3.0.0-4.  From the looks of it, `ember-classy-page-object` is still a dependency in that version: https://github.com/Addepar/ember-table/blob/v3.0.0-4/package.json#L33

**Comment by mixonic** [comment] 2021-01-21 21:04
@danwenzel thanks for checking. We've got several codebases working with that beta and Ember 3.24. I confirmed one is running well with these packages:

```
yarn list v1.22.10
├─ ember-classy-page-object@0.6.1
├─ ember-cli-page-object@1.15.4
├─ ember-qunit@5.1.1
├─ ember-source@3.24.1
└─ qunit@2.14.0
Done in 1.14s.
```

In fact I think QUnit 2.14.0 is the latest release of QUnit, not 5.x? I think that is confirmed by https://github.com/qunitjs/qunit/blob/master/History.md I presume you're looking at `ember-qunit`.

Can you see where your app's versions differ?

**Comment by danwenzel** [comment] 2021-01-21 21:48
Ah yeah, my bad:  I did mean `ember-qunit` 5.  I'll update the title

I did try it with all of those versions, and am still seeing the issue.  It's this issue here: https://github.com/san650/ember-cli-page-object/issues/524

not sure why you're not seeing it... 🤔

**Comment by ro0gr** [comment] 2021-01-25 16:18
Hey! 👋 

> I did try it with all of those versions, and am still seeing the issue. It's this issue here: san650/ember-cli-page-object#524

Turns out, due to some of refactorings, starting from 1.16.x, ec-page-object started explictly [depending](https://github.com/san650/ember-cli-page-object/commit/60ec536dae3d87d5b056e20907c1d77ade1c060b#diff-cf0f4391ac6c63e159f0f77ef3ac998c938061011a154c223a853051cac4d17cR17) on the `ember-test-helpers/wait`, which causes the issue with `@ember/test-helpers@2` needed for the `ember-qunit@5` 😅 

This has been solved now in the ember-cli-page-object@1.17.5. You should be able to upgrade to the ember-qunit@5 now. Sorry for inconveniences!

> However, ember-table has a dependency on ember-classy-page-object

I can see it may cause some problems in the future, due to indefinite merge behavior of the ember-cli. So if I have ec-page-object, as a dependency in my APP, I could get ec-page-object coming from the ember-classy-page-object. I'm not sure if it would overlap with an upcoming ec-page-object@v2 in some way.

It feels like having ember-classy-page-object as a `devDependency` may worth to consider.

**Comment by mixonic** [comment] 2021-01-25 16:36
I strongly agree that ember-classy-page-object and ember-cli-page-object are risky dependencies. In this project and others I've spent a lot of time on maintenance issues around them. I don't expect in the 3.0 project we will attempt to move away from them though, as many consumers (at least Addepar) leverage those test helpers quite aggressively. The test suite in this codebase also uses them aggressively. Migrating away will take serious intent and effort.

Thank you for the follow up @ro0gr. I'm going to mark this closed. I'll also do a quick experiment to see if we can update the dependencies of ember-table to the latest of these libraries successfully and easily, at the least.

**Closed by mixonic** 2021-01-25 16:36 UTC

**Comment by ro0gr** [comment] 2021-01-25 21:39
@mixonic let me know if I can help you with your quick experiment. 

TBH, I think providing base page objects for a complex component library is not such a bad direction. I just meant, it should not probably require all the users(even who don't use page objects at all) to pay the cost for it, so {dev,peer}Dependency seems to have somewhat more sense.
