### ISSUE TITLE
Support Ember 4.0

### ISSUE THREAD

**Issue by mixonic** [Addepar/ember-table#897] opened 2021-07-23 16:29 UTC
Ember 4.0 is currently the canary channel, and it fails. There are likely several deprecations in 3.x which become removals in 4.0 and so break the library.

* [ ] 👇 Remove any deprecations which can be removed without breaking compat in `master`
* [ ] 👇 Identify deprecations which are a breaking change and consider them for a major version bump
* [x] `hasBlock` https://github.com/Addepar/ember-table/pull/884

**Comment by kpfefferle** [comment] 2021-07-23 19:16
One deprecation removal already in flight for `hasBlock`: #884

**Comment by rwwagner90** [comment] 2021-07-28 03:58
@mixonic I think ember-classy-page-object is one thing that is incompatible with modern Ember currently. I've been seeing babel errors for it. I do see the master branch has ember-cli-babel 7 though https://github.com/Addepar/ember-classy-page-object/blob/master/package.json#L23

Any plans to release a new version and update that here?

**Comment by johanrd** [comment] 2021-11-18 10:16
Supporting `Ember 4.0` may be a good occasion cut the cord for still supporting `Ember 2.8`.

In my view, the following could be a good fit for an `Ember Table 4.0` release:
• **Update dependencies** along the lines of the work being done at https://github.com/rwwagner90/ember-table 
• **Deprecate Ember global**, see https://github.com/rwwagner90/ember-table/pull/1
• **Replace hasBlock usage with has-block helper** (https://github.com/Addepar/ember-table/pull/884)
• **Deprecate Property Fallback Lookup** (no implicit this) (https://github.com/Addepar/ember-table/pull/907)
• **Use pre-built styles** (https://github.com/Addepar/ember-table/pull/900)

Regarding minimum ember-source support, updating to `"ember-test-selectors": 6.0.0` would for instance require at least `Ember 3.8` (as I understand it). 

There is seemingly enough momentum around this to not need to wait too long for a breaking release. As mentioned by @ctjhoa in https://github.com/Addepar/ember-table/pull/900 these can of course be portioned into several smaller breaking releases. However, I don't think we are very far from a breaking release that also supports `Ember 4.0`.

**Comment by rwwagner90** [comment] 2021-11-22 14:51
@johanrd the problem is, I think Addepar wants to keep the master branch and latest release in line with their supported versions for all of their apps. I have proposed that these addons are stable enough on their current versions, to support legacy Ember, but the problem is if new features want to be added, for example, something like column sorting, they want that to work across all their apps.

I would love to hear from @kpfefferle and @mixonic about this. I know @mixonic is on paternity leave though. I think our best option may be forking some of these repos and releasing as alternate packages, which is unfortunate, but we have a lot of things breaking here with Ember 4.

**Comment by kpfefferle** [comment] 2021-11-23 16:16
@rwwagner90 I own an application at Addepar that currently runs on Ember 3.28 and will be making a strong push to upgrade to Ember 4.0 by the end of the year. In order for that to happen, we will have to push this work forward on ember-table. I'd expect us to at least have a future-looking branch and consumable prerelease version by the end of the year.

Apologies that we haven't had the bandwidth to keep ember-table on the bleeding edge as 4.0 approached, but our timeline for getting this unblocked should be measured in weeks (not months). We very much appreciate the PRs that are awaiting review - these set us up well for making quick progress here once we start moving.

**Comment by rwwagner90** [comment] 2021-11-23 17:36
@kpfefferle gotcha, sounds good! I have forked a few of the repos that needed updates, since I was under the impression we wouldn't be able to drop 2.8, but if we are thinking of dropping it, I have a lot of things I would be happy to open PRs for!

**Comment by billybonks** [comment] 2021-12-01 16:39
+1, would love to see a 4.0 branch that we can start merging things into. @rwwagner90 seems to have done a lot of work around this, but as there is not master for 4.0 it's hard to see what else needs doing.

We can just work on that branch until the team is happy to cut a new major release, that supports 4.0

**Comment by kpfefferle** [comment] 2021-12-03 15:42
I have created a `4.0-beta` branch which drops the ember-try scenario for 2.8 and opened draft PR #919

I have retargeted my own has-block PR #884 to this beta branch to get the ball rolling on deprecation removals needed for 4.0.

Any PRs that address 3.x deprecations that are not compatible with 2.8 support may now target the `4.0-beta` branch. If we can address the 3.x deprecations and re-enable the 4.0 `ember-release` scenario on that branch, then I will cut a beta release that supports Ember 4.0! 🚀

Thanks to all y'all for your efforts and enthusiasm for pushing this forward!

**Comment by rwwagner90** [comment] 2021-12-03 16:25
@kpfefferle if you let me know when all the existing stuff is merged, I would be happy to open a PR with the remaining changes, just don't want to duplicate work!

**Comment by kpfefferle** [comment] 2021-12-06 16:10
@rwwagner90 #884 and #900 have been merged to the `4.0-beta` branch. #907 has been merged to `master` (since it's backwards-compatible) and the `4.0-beta` branch has been rebased to pick up those changes.

If I've overlooked any current PRs, please let me know.

**Comment by kpfefferle** [comment] 2021-12-10 16:55
I just published `4.0.0-beta.0` as an initial prerelease of the `4.0-beta` branch

**Comment by billybonks** [comment] 2021-12-20 07:52
thanks @kpfefferle can we consider https://github.com/Addepar/ember-table/issues/903 as part of the 4.0.0 release

**Comment by kpfefferle** [comment] 2021-12-20 14:51
@billybonks We merged https://github.com/Addepar/ember-table/pull/900 into the `4.0-beta` branch which removes the ember-cli-sass dependency from consuming apps. Sass is still in use by the test app after that PR, but the published `4.0-beta.0` prerelease already includes removing ember-cli-sass for consumers.

**Comment by johanrd** [comment] 2021-12-21 17:10
@kpfefferle great, thanks!

Testing the `4.0-beta.0` branch, it seems like the only parts missing to be `Ember 4.0` compatible is to fine tune some of the work done by @rwwagner90 over at https://github.com/rwwagner90/ember-table
• Update dependencies (at least `ember-test-selectors`)
• Deprecate Ember global (rwwagner90#1)

**Comment by rwwagner90** [comment] 2021-12-21 19:05
@johanrd I have a PR open to update test selectors, but it isn't passing CI for some reason.

**Comment by DanMonroe** [comment] 2021-12-21 19:29
I'm playing with it now to see if I can fix the CI issues

**Comment by johanrd** [comment] 2021-12-21 20:05
@DanMonroe Great! 

Had a brief look myself. It may be related to the deprecation of automatic attribute bindings in `ember-test-selectors: 6.0.0` (see https://github.com/simplabs/ember-test-selectors/pull/713).

**Comment by DanMonroe** [comment] 2021-12-21 21:07
Thanks for #924   I've been doing that for all our internal addons while everyone is gone on vacation.

**Comment by rwwagner90** [comment] 2022-02-01 13:49
Global Ember is from ember-test-selectors, IIRC

**Comment by DanMonroe** [comment] 2022-02-02 18:34
FYI, I am working on all of this right now.

**Comment by kpfefferle** [comment] 2022-02-24 16:22
Thanks to a bunch of recent work by @DanMonroe, we released [`4.0.0-beta.4`](https://github.com/Addepar/ember-table/releases/tag/v4.0.0-beta.4) today with full Ember 4 compatibility! 🎉

- https://github.com/Addepar/ember-table/pull/919

We'll probably keep this as a prerelease for a little while so people can test it out and hope that some of the upstream prerelease dependencies we are using in that branch can reach stable before we make ember-table v4 the stable release on `master`.

**Closed** 2022-05-18 13:33 UTC
