### ISSUE TITLE
hasFooter and {{ember-table-footer}} (alpha release)

### ISSUE THREAD

**Issue by tythewebguy** [Addepar/ember-table#451] opened 2017-11-22 16:52 UTC
I'm trying to figure out the structure of things in the alpha release. Adding hasFooter=true adds a fixed footer to the table that is just a repeat of the header. I tried to change this by adding this code after the tree-table-row block in the demo.hbs file (using the dummy app):

```
    {{#ember-table-footer}}
      Hello world
    {{/ember-table-footer}}
```
The results are not what I expected. I'm getting a "table" footer repeated after every row inside the table.

![image](https://user-images.githubusercontent.com/1933030/33139291-b022130a-cf61-11e7-9514-9e4fa51c9519.png)

What am I missing here?

**Comment by pzuraq** [comment] 2017-11-22 17:22
Hey @tythewebguy, it seems like this is a duplicate of #450. Going to close that issue in favor of this one, please try to give us some time to triage issues before opening duplicates, we are watching but we’re also busy 🙂

As for the behavior and structure, the yield in `ember-table` is only for the rows. There is no way to yield a footer or header manually, we will likely add that ability in ember-table v3. 

We’re currently still in alpha, which means this is a very early version of ember-table v2 and not all of the functionality from v1 has been implemented yet, and there is likely some functionality that will change or won’t make it. @billy-addepar can say more about the footer and whether or not it works yet, and how it works if so, but the answer may simply be that it is broken currently.

**Comment by billy-addepar** [comment] 2017-11-23 00:31
I am taking a look at the footer issue. This functionality could be broken after some code refactoring.

**Comment by billy-addepar** [comment] 2017-12-02 00:13
This is fixed on master. After some discussion, we change our API footer as follow
- Remove `hasFooter` field in ember table component. If you want to use footer, pass an array of `footerRows` instead. An array means you can have multiple footer rows. 
- `footerRows` should have similar structure to table body rows and use `valuePath` in column to retrieve data for each cell. 
- You can have custom footer by passing `footerComponent` in each column. 

I close this issue now. Let me know if you have other issue

**Closed by billy-addepar** 2017-12-02 00:13 UTC
