### ISSUE TITLE
Totals row for alpha, like "Tree & financial table" example?

### ISSUE THREAD

**Issue by tythewebguy** [Addepar/ember-table#448] opened 2017-11-21 23:55 UTC
It looks like the alpha release doesn't have a way of fixing a row at the bottom of the table to display column totals, like the *Tree & financial table* example. Is this correct? Is anything like this coming soon?

**Comment by pzuraq** [comment] 2017-11-22 17:24
Duplicate of #451

**Closed by pzuraq** 2017-11-22 17:24 UTC
