### ISSUE TITLE
does ember-table support dynamic contents

### ISSUE THREAD

**Issue by TheLooseCannon** [Addepar/ember-table#796] opened 2019-12-12 10:35 UTC
will it support the row argument which is bound to a tracked variable?

right now when im doing it im getting the error 

> Error: Assertion Failed: You attempted to update `rows` on `<(unknown):ember472>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
> 
> `rows` was first used:

whats the solution

**Comment by wuarmin** [comment] 2019-12-12 12:28
Checkout #795

**Comment by JamesS-M** [comment] 2020-01-15 15:44
I'm running into this error as well. I've checked out #795, which isn't working for me. Any progress on fixing this issue?

**Comment by mixonic** [comment] 2020-01-15 17:08
Closing as a dupe of https://github.com/Addepar/ember-table/issues/795 please re-open if that is in error.

**Closed by mixonic** 2020-01-15 17:08 UTC
